### ISSUE TITLE
npm-mirror fails if it reads a manifest without a dist

### ISSUE THREAD

**Issue by 7Grok** [mozilla-b2g/npm-mirror#11]
The last lines before it blows up are 
npm-mirror:SyncManager http-signature needs assert-plus@0.1.2 +71ms
  npm-mirror:SyncManager http-signature needs asn1@0.1.11 +1ms
  npm-mirror:SyncManager http-signature needs ctype@0.5.2 +0ms
  npm-mirror:SyncManager hawk needs hoek@0.9.1 +383ms
  npm-mirror:SyncManager hawk needs boom@0.4.2 +0ms
  npm-mirror:SyncManager hawk needs cryptiles@0.2.2 +0ms
  npm-mirror:SyncManager hawk needs sntp@0.2.4 +0ms
  npm-mirror:SyncManager form-data needs combined-stream@0.0.4 +32ms
  npm-mirror:SyncManager object-keys needs foreach@2.0.4 +65ms
  npm-mirror:SyncManager object-keys needs indexof@0.0.1 +0ms
  npm-mirror:SyncManager object-keys needs is@0.2.6 +0ms
  npm-mirror:SyncManager combined-stream needs delayed-stream@0.0.5 +85ms
  npm-mirror:SyncManager maybe make 442 dirs +93ms

/usr/lib/node_modules/npm-mirror/lib/syncmanager.js:308
          'shasum': packageRoot.versions[latest].dist.shasum,
                                                ^
TypeError: Cannot read property 'dist' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/npm-mirror/lib/syncmanager.js:308:49)
    at Object.Download.download (/usr/lib/node_modules/npm-mirror/lib/download.js:45:26)
    at Object.<anonymous> (/usr/lib/node_modules/npm-mirror/lib/syncmanager.js:278:21)
    at Array.forEach (native)
    at Object.SyncManager.downloadPackageRootObjects (/usr/lib/node_modules/npm-mirror/lib/syncmanager.js:274:14)
    at Object.SyncManager.download (/usr/lib/node_modules/npm-mirror/lib/syncmanager.js:251:10)
    at Object.<anonymous> (/usr/lib/node_modules/npm-mirror/lib/syncmanager.js:86:16)
    at onMaybeMkdir (/usr/lib/node_modules/npm-mirror/lib/syncmanager.js:238:30)
    at /usr/lib/node_modules/npm-mirror/lib/maybemkdir.js:13:26
    at Object.cb [as oncomplete](fs.js:168:19)

**Comment by lambdabaa** [comment]
The short explanation is that I can write a patch for this later today. The long version is that packages come with a json "versions" object which is a map from published versions to manifests for those versions. Each npm manifest is supposed to have a "dist" field which gives you a link to a tarball along with a shasum to check the tarball. One of the ones you were downloading didn't. For an example, look at http://registry.npmjs.org/mocha.

**Comment by lambdabaa** [comment]
269e29db9f0b07bf5c2955bc074616cbbc39e275 should fix this. Give it a try again and let me know how it goes @BobTheBotMaker

**Comment by lambdabaa** [comment]
The fix got published in npm-mirror@1.1.1
