### ISSUE TITLE
Unable to specify local URL

### ISSUE THREAD

**Issue by GJKrupa** [mozilla-b2g/npm-mirror#24]
Attempting to specify a local URL for the hostname property results in a URL validation error.  For example:

npm-mirror --master http://registry.npmjs.org/ --hostname http://box29:8080/ --root d:\mirror --manifests D:\project1\package.json

Results in
C:\Users\XXX\AppData\Roaming\npm\node_modules\npm-mirror\node_modules\validator\lib\validator.js:25
    throw new ValidatorError(msg);
          ^
ValidatorError: Invalid URL
    at new exports.ValidatorError (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm-mirror\node_modules\validator\lib\validator.
js:6:11)
    at Validator.error (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm-mirror\node_modules\validator\lib\validator.js:25:11)
    at Validator.(anonymous function) [as isUrl](C:UsersXXXAppDataRoamingnpmnode_modulesnpm-mirrornode_modulesvalidator
libvalidator.js:63:33)
    at main (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm-mirror\bin\npm-mirror:106:19)
    at C:\Users\XXX\AppData\Roaming\npm\node_modules\npm-mirror\bin\npm-mirror:152:5
    at downloadManifests (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm-mirror\bin\npm-mirror:38:12)
    at Object.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm-mirror\bin\npm-mirror:147:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

This doesn't happen with localhost though.

**Comment by aeria** [comment]
Similarly I am finding custom domain suffixes are not working. --hostname ending in .com does, but say... .c3po does not
